<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="vinTestngStart.TestvinExam1" tests="5" time="0.020" ignored="5" failures="1" timestamp="23 Mar 2025 12:12:05 GMT" skipped="2" hostname="Vinesh-PC" errors="0">
  <testcase name="test3" time="0.003" classname="vinTestngStart.TestvinExam1">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.002" classname="vinTestngStart.TestvinExam1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at vinTestngStart.TestvinExam1.test3(TestvinExam1.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test2" time="0.011" classname="vinTestngStart.TestvinExam1"/>
  <testcase name="test6" time="0.002" classname="vinTestngStart.TestvinExam1"/>
  <testcase name="test3" time="0.002" classname="vinTestngStart.TestvinExam1">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test8" classname="vinTestngStart.TestvinExam2">
    <skipped/>
  </testcase> <!-- test8 -->
  <testcase name="test10" classname="vinTestngStart.TestvinExam2">
    <skipped/>
  </testcase> <!-- test10 -->
  <testcase name="test1" classname="vinTestngStart.TestvinExam1">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test4" classname="vinTestngStart.TestvinExam1">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase name="test5" classname="vinTestngStart.TestvinExam1">
    <skipped/>
  </testcase> <!-- test5 -->
</testsuite> <!-- vinTestngStart.TestvinExam1 -->
